Resources:
  iamuser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: whisupport
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      LoginProfile:
        Password: "@cL0uDgUrU2020"
        PasswordResetRequired: false
  iamkeys:
    DependsOn: iamuser
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: whisupport
Outputs:
  adminakid:
    Description: Support Access Key ID
    Value: !Ref iamkeys
  adminsecretkey:
    Description: Support Secret Access Key
    Value: !GetAtt iamkeys.SecretAccessKey
